// ============================================================
// Doppelgänger — Phase 0 Validierung: DEINE DATEN
// ============================================================
// Vollständiges Test-Dataset: 5 Personas x 50 Fragen (250 Antworten).
// Quelle: test-dataset-komplett.md
//
// Personas:
//   Kai      = maximal knapp, klein, keine Satzzeichen, lakonisch
//   Elena    = begeistert, !!!, Emojis, "haha"/"omg"
//   Thorsten = schlampig getippt, Tippfehler, norddeutsch
//   Ines     = saubere Saetze, trocken-ironisch, nie Emojis
//   Bernd    = bairisch gefaerbt, herzlich-derb, mittellang
//
// Leere Antworten ("") werden vom Script uebersprungen.
// ============================================================

module.exports = {

  // ---- Fragen (f1-f50 aus dem Fragenpool) ----
  fragen: {
    f1:   "Was ist dein unnötigstes Talent?",
    f2:   "Welche App auf deinem Handy würdest du als Letztes löschen?",
    f3:   "Was war dein erster Gedanke heute Morgen?",
    f4:   "Welches Gericht könntest du jeden Tag essen?",
    f5:   "Was wolltest du als Kind unbedingt werden?",
    f6:   "Welche Serie hast du zuletzt komplett durchgesuchtet?",
    f7:   "Was steht ganz oben auf deiner Reise-Wunschliste?",
    f8:   "Welchen Song hörst du heimlich viel zu oft?",
    f9:   "Was ist das Beste, was du dir dieses Jahr gekauft hast?",
    f10:  "Wofür gibst du zu viel Geld aus?",
    f11:  "Was kannst du überraschend gut kochen?",
    f12:  "Welcher Geruch macht dich sofort glücklich?",
    f13:  "Was war dein schönster Urlaubsmoment aller Zeiten?",
    f14:  "Welches Hobby würdest du anfangen, wenn Zeit keine Rolle spielen würde?",
    f15:  "Was ist dein Lieblingswort?",
    f16:  "Mit welcher berühmten Person würdest du gerne einen Kaffee trinken?",
    f17:  "Was machst du, wenn du eine Stunde komplett für dich hast?",
    f18:  "Was wäre dein letztes Wort vor der Hinrichtung?",
    f19:  "Womit würdest du eine Zombie-Apokalypse überleben?",
    f20:  "Was wäre dein Gefängnis-Spitzname?",
    f21:  "Welche Superkraft hättest du gerne — aber nur in nutzloser Mini-Version?",
    f22:  "Was würdest du tun, wenn du für einen Tag unsichtbar wärst?",
    f23:  "Welchen Titel hätte der Film über dein Leben?",
    f24:  "Was würde deine KI-Assistentin hinter deinem Rücken über dich sagen?",
    f25:  "Welches Tier wärst du in einem früheren Leben gewesen?",
    f26:  "Was wäre dein Spezialgericht in der Hölle-Küche?",
    f27:  "Womit würdest du sofort viral gehen, wenn du müsstest?",
    f28:  "Was würdest du als Erstes tun, wenn du Bundeskanzler/in wärst?",
    f29:  "Welchen völlig unnötigen Weltrekord würdest du aufstellen?",
    f30:  "Was wäre der Name deiner Band — und welches Instrument spielst du?",
    f31:  "Wofür würdest du nachts um 3 Uhr aufstehen, ohne zu meckern?",
    f32:  "Was würde ein Alien über die Menschheit denken, wenn es nur dein Handy findet?",
    f33:  "Welcher Gegenstand in deiner Wohnung hat die beste Geschichte?",
    f34:  "Was wäre dein Kampfschrei beim Betreten eines Meetings?",
    f35:  "Welchen historischen Moment hättest du gerne live gesehen?",
    f36:  "Was würdest du mit einer Million machen — innerhalb von 24 Stunden?",
    f37:  "Was war deine peinlichste Autokorrektur-Panne?",
    f38:  "Welche Ausrede hast du am häufigsten benutzt, um eine Party früher zu verlassen?",
    f39:  "Was googelst du, was du niemals laut zugeben würdest?",
    f40:  "Welche Nachricht hast du mal an die falsche Person geschickt?",
    f41:  "Was ist das Kindischste, das du regelmäßig tust?",
    f42:  "Welche unpopuläre Meinung vertrittst du mit voller Überzeugung?",
    f43:  "Was war dein schlimmster Fashion-Fehler?",
    f44:  "Wen aus dieser Runde würdest du anrufen, wenn du eine Leiche verstecken müsstest — und warum?",
    f45:  "Was war die absurdeste Lüge, mit der du durchgekommen bist?",
    f46:  "Welchen Trend hast du mitgemacht und bereust es heute?",
    f47:  "Was würdest du nie wieder bei einem ersten Date machen?",
    f48:  "Welche Angewohnheit von dir würde deine Mitbewohner/Partner in den Wahnsinn treiben?",
    f49:  "Was ist das Verrückteste, was du je für Geld oder eine Wette getan hast?",
    f50:  "Welche Nachricht in deinem Handy-Verlauf wäre am schwersten zu erklären?",
  },

  // ---- Antworten pro Person ----
  antworten: {

    "Kai": {
    f1:   "rückwärts einparken beim ersten versuch",
    f2:   "wecker. leider",
    f3:   "nein",
    f4:   "spaghetti. einfach spaghetti",
    f5:   "müllmann. wegen mitfahren",
    f6:   "dark. zweimal. versteh es immer noch nicht",
    f7:   "japan. wegen essen",
    f8:   "atemlos. fragt nicht",
    f9:   "heizdecke. lebensverändernd",
    f10:  "essen liefern lassen obwohl kühlschrank voll",
    f11:  "risotto. überrascht mich selbst jedes mal",
    f12:  "regen auf asphalt",
    f13:  "hängematte. drei stunden. kein handy",
    f14:  "segeln. keine ahnung warum",
    f15:  "feierabend",
    f16:  "keanu reeves. einfach schweigen zusammen",
    f17:  "nichts. aktiv nichts",
    f18:  "war nett",
    f19:  "keller. ravioli. fertig",
    f20:  "der stille",
    f21:  "teleportation. aber nur 30 cm",
    f22:  "im büro sitzen. zuhören. notizen machen",
    f23:  "kommt noch",
    f24:  "fragt viel. dankt nie",
    f25:  "katze. begründung unnötig",
    f26:  "lauwarme pommes",
    f27:  "video wie ich 10 minuten schweige. asmr oder so",
    f28:  "meetings auf 15 minuten begrenzen. per gesetz",
    f29:  "längstes schweigen in einer telko",
    f30:  "die pause. triangel",
    f31:  "käsebrot",
    f32:  "spezies kommuniziert in daumen hoch",
    f33:  "ein einzelner ski. langes thema",
    f34:  "das hätte eine mail sein können",
    f35:  "mauerfall. wegen stimmung",
    f36:  "anzahlung haus. rest ruhe",
    f37:  "\"lieber gruß\" wurde \"liebes gruselwesen\". an den chef",
    f38:  "keine. ich gehe einfach",
    f39:  "wie alt ist [promi]. täglich",
    f40:  "screenshot vom chat. an den chat",
    f41:  "treppen immer zwei stufen. immer",
    f42:  "kartoffelsalat ohne mayo",
    f43:  "sonnenbrille im club. 2009. innen",
    f44:  "thorsten. hat werkzeug, fragt nicht",
    f45:  "\"bin gleich da\"",
    f46:  "dutt. mit meinen haaren",
    f47:  "kino. man lernt nichts. man schweigt nur",
    f48:  "schränke. offen. alle",
    f49:  "eine woche nur in reimen geredet. 50 euro",
    f50:  "\"hast du den bagger noch\"",
    },

    "Elena": {
    f1:   "Ich kann JEDEN Songtext von 2010 auswendig haha komplett nutzlos 🎤",
    f2:   "Spotify!!! Ohne Musik geht bei mir gar nichts 🎧",
    f3:   "Yay Freitag!!! Und dann ist mir eingefallen dass Donnerstag ist 😅",
    f4:   "Sushi!!! Frag mich nicht wie ich das bezahlen soll aber Sushi 🍣",
    f5:   "Delfintrainerin!!! Ich hatte sogar schon Namen für meine Delfine 🐬",
    f6:   "Emily in Paris haha JA ich weiß!!! Aber es ist so schön kitschig 🥐",
    f7:   "Bali!!! Die Fotos, die Strände, die Smoothie Bowls omg 🌴",
    f8:   "Alles von Taylor Swift haha ist das noch heimlich?? 🎶",
    f9:   "Mein E-Bike!!! Ich fühl mich so sportlich obwohl der Motor alles macht haha 🚲",
    f10:  "Kerzen und Deko haha meine Wohnung sieht aus wie ein Interior-Account 🕯️",
    f11:  "Pancakes!!! Sonntags ist bei mir Pancake-Tag, nicht verhandelbar 🥞",
    f12:  "Frisch gebackene Zimtschnecken omg ich werd schwach 🤤",
    f13:  "Sonnenaufgang am Strand in Portugal!!! Ich hab geweint, kein Witz 🌅",
    f14:  "Töpfern!!! Ich stell mir das so entspannend vor mit Podcast und Ton überall 🏺",
    f15:  "Kuddelmuddel haha das klingt einfach so süß!! 💕",
    f16:  "Taylor Swift!!! Ich hätte ungefähr 800 Fragen 😍",
    f17:  "Badewanne mit Kerzen und Musik!!! Selfcare ist wichtig Leute 🛁",
    f18:  "OMG sagt meiner Familie ich hab sie lieb!!! 😭❤️",
    f19:  "Mit meinem Hund und ganz viel Optimismus!! Und Pfefferspray haha 🐕",
    f20:  "Glitzer!!! Weil ich auch im Knast gute Laune verbreite haha ✨",
    f21:  "Gedanken lesen aber nur von Hunden!!! Wäre eh nur \"Futter\" und \"Ball\" haha 🐶",
    f22:  "Hinter die Kulissen von nem Konzert!!! Backstage einfach alles angucken 🎫",
    f23:  "\"Sie hat es wieder vergessen\" haha eine Tragikomödie 🎬",
    f24:  "Dass ich sie für ALLES frage haha sogar was ich kochen soll 🙈 sorry Siri!!",
    f25:  "Ein Otter!!! Die halten Händchen beim Schlafen omg 🦦",
    f26:  "Veggie-Auflauf wo GENAU EIN Stück Fleisch drin versteckt ist haha 😈",
    f27:  "Hundevideos!!! Mein Hund macht so ein Ding mit dem Kopf, das wäre SOFORT viral 🐕",
    f28:  "Mehr Feiertage!!! Wir haben einfach zu wenig, das ist Fakt 🎉",
    f29:  "Die meisten Emojis in einer einzigen Nachricht!!! 🏆🎉😂✨🙌",
    f30:  "Glitter Chaos und ich sing natürlich!!! Falsch aber laut 🎤",
    f31:  "Polarlichter!!! Dafür steh ich SOFORT auf, ohne Diskussion 🌌",
    f32:  "Dass wir Hunde anbeten haha bei 90% Hundefotos verständlich 🛸",
    f33:  "Eine Schneekugel aus Paris die ich dreimal verschenkt hab und immer wieder zurückbekommen hab haha 🎁",
    f34:  "GUTE LAUNE FÜR ALLE!!! Ob ihr wollt oder nicht haha ☀️",
    f35:  "Die erste Mondlandung!!! Stellt euch das vor, ALLE haben gleichzeitig hingeguckt 🌕",
    f36:  "Erstmal alle anrufen und schreien!!! Dann Familie einladen, dann Weltreise buchen 🌍",
    f37:  "Statt \"Meeting verschieben\" hab ich \"Meeting verlieben\" geschrieben omg an den GANZEN Verteiler 🙈",
    f38:  "\"Mein Hund ist alleine\" haha funktioniert IMMER und ist nichtmal gelogen 🐕",
    f39:  "Sternzeichen-Kompatibilität haha JA ich glaub nicht dran aber ich gucke trotzdem 🔮",
    f40:  "Ich hab über das Geschenk für meine Mama geschrieben... AN meine Mama 😅 Überraschung ruiniert haha",
    f41:  "Ich red mit meinem Hund in ner Babystimme und er hat ein eigenes Lied!!! 🎵",
    f42:  "Ananas auf Pizza ist MEGA und ich lass mir das nicht ausreden!!! 🍍🍕",
    f43:  "Neon-Leggings ZU neon Top!!! Es gibt Fotos und sie verfolgen mich 📸",
    f44:  "Ines!!! Die wirkt so als hätte sie für alles einen Plan haha 😬",
    f45:  "Dass ich die Torte selbst gebacken hab... war vom Bäcker, ich hab nur Puderzucker draufgemacht 🎂",
    f46:  "Diese Eiswürfel-Gesichtsmasken auf Insta!!! Hab mir fast Frostbeulen geholt haha 🧊",
    f47:  "Klettern!!! Ich hab geschwitzt, geweint und um Hilfe gerufen. ERSTES Date!! 🧗",
    f48:  "Ich fang 5 Serien gleichzeitig an und will über ALLE reden 📺",
    f49:  "Ich hab auf nem Volksfest Karaoke gesungen vor 200 Leuten!!! Für 20 Euro und nen Crepe 🎤",
    f50:  "\"Bring Glitzer mit, FRAG NICHT\" haha es gibt Kontext aber er hilft nicht 🤫",
    },

    "Thorsten": {
    f1:   "ich kann mit den ohren wackeln. hat mir beruflich noch nix gebracht aber man weis ja nie",
    f2:   "kleinanzeigen. da häng ich mehr rum als auf insta, is wie flohmarkt nur ohne rausgehn",
    f3:   "wo is mein handy. lag aufm gesicht. klassiker",
    f4:   "döner mit allem und scharf. gibts bei uns anner ecke, der mann kennt mich schon",
    f5:   "lokführer. dann hab ich gehört wie früh die aufstehn müssn und hab umgeplant",
    f6:   "haus des geldes nochmal von vorne. wuste gar nich mehr wer am ende übrig bleibt",
    f7:   "mitm wohnmobil nach norwegen. einfach losfahrn und gucken wie weit man kommt",
    f8:   "wonderwall. ich weis. aber wenn der refrain kommt bin ich halt dabei",
    f9:   "akkuschrauber mit zwei akkus. einer läd immer. das system funktioniert",
    f10:  "kram bei kleinanzeigen den ich \"reparieren\" will. mein keller is ne werkstatt für aufgegebene projekte",
    f11:  "labskaus. klingt komisch sieht komisch aus schmeckt aber bombe",
    f12:  "moin, ganz klar: grill der grade angeht. nachbars grill zählt auch",
    f13:  "mitm kumpel inner finnischen sauna eingeschneit worden. mussten zwei tage bleiben. beste zwei tage",
    f14:  "nen alten bulli restauriern. hab schon drei youtube kanäle dazu abonniert das zählt ja fast",
    f15:  "plietsch. norddeutsch für schlau. bin ich zwar nich immer aber das wort is geil",
    f16:  "buddy ausm fernsehn der die schrottplätze abklappert. der hätt geschichten",
    f17:  "garage. irgendwas schrauben oder sortiern. meine frau nennts verstecken ich nenns wartung",
    f18:  "moin erstmal. ne im ernst, sagt meiner muddter das essen war nich so schlimm wie ich immer gesgat hab",
    f19:  "moin, also erstmal zum baumarkt, dann zur tanke, dann ab nach skandinavien. zombies könn nich schwimmen glaub ich",
    f20:  "keine ahnung, wahrscheinlich \"der mit dem handy\" weil ich als einzigster eins reingeschmugelt hätte",
    f21:  "röntgenblick aber nur durch frischhaltefolie",
    f22:  "beim nachbarn gucken wie der seine hecke SO grade kriegt. der hat n geheimnis ich weis es",
    f23:  "\"läuft bei dem (technisch gesehen)\". untertitel: warum liegt hier überhaupt werkzeug",
    f24:  "\"der typ hat mich 5 mal gefragt wie man rissoto schreibt und es dann trozdem falsch geschriben\"",
    f25:  "möwe. laut, frech, klaut pommes. passt",
    f26:  "grünkohl ohne wurst. einfach nur grünkohl. die leute solln leiden",
    f27:  "ich repariere live nen toaster und es explodiert. ungeplant aber content is content",
    f28:  "baumärkte sonntags auf. das volk braucht das. ICH brauch das",
    f29:  "schnellstes zusammenbaun von nem ikea regal OHNE anleitung. mit übrigen schrauben natürlich",
    f30:  "rostlaube. schlagzeug, weil da kann man nix falsch stimmen",
    f31:  "wenn n kumpel anruft und sagt sein auto springt nich an. ehrensache. werkzeug liegt eh im flur",
    f32:  "\"diese lebensform fotografiert kaputte sachen und schickt sie an andere mit der frage: kriegt man das noch hin\"",
    f33:  "ne parkbank-latte. offiziell gefunden. mehr sag ich dazu nich",
    f34:  "moin moin, wer hat kaffee und wer hat schuld",
    f35:  "als der typ das rad erfunden hat. ob der wuste was er da losgetreten hat",
    f36:  "ne halle kaufen. einfach ne halle. für projekte. meine frau liest das hoffentlich nich",
    f37:  "wollte \"moin chef\" schreiben, stand da \"mein schatz\". hr war kurz involviert",
    f38:  "\"muss morgen früh raus\" und dann sitz ich bis 2 inner garage. is ja nich gelogen, garage is früh raus",
    f39:  "\"geräusch waschmaschine normal\" mit geräuschbeschreibung in worten. klong klong rattata",
    f40:  "hab mich über meinen schwager aufgeregt. beim schwager. wir reden jez wieder, war n langer weg",
    f41:  "wenn die mikrowelle bei 0:01 stoppt fühl ich mich wie n bombenentschärfer",
    f42:  "glühwein schmeckt auch im sommer, hab ich getestst, läuft",
    f43:  "angelhose aufm standesamt. war praktisch gemeint, kam nich so an",
    f44:  "bernd. der kennt bestimmt ne abgelegene almhütte und redet nich",
    f45:  "hab in der schule gesagt mein referat is auf nem usb stick der durch die wäsche kam. hatte nie n referat UND nie n stick",
    f46:  "fidget spinner. hatte SIEBEN. sieben stück. wofür",
    f47:  "zum essen zu mir eingeladen und wollte flambieren. feuerwehr war nett, date kam nich wieder",
    f48:  "ich sammel schrauben in gläsern. überall gläser. \"die brauch ich noch\" hab ich 2019 gesagt",
    f49:  "bin im winter in die nordsee. komplett. für n döner. WÜRD ICH WIEDER TUN",
    f50:  "\"ja moin, die ziege is wieder da. selbe wie letztes mal. bring brot\"",
    },

    "Ines": {
    f1:   "Ich erkenne Schriftarten auf Speisekarten. Niemand hat je danach gefragt.",
    f2:   "Die Notizen-App. Dort lagern Einkaufslisten aus drei Jahren, ein Gedicht und eine Geschäftsidee.",
    f3:   "Ich erwog kurz, das Konzept „Morgen\" grundsätzlich abzulehnen.",
    f4:   "Käsebrot. Es ist ehrlich, verlässlich und hat mich nie enttäuscht. Mehr als manche Menschen.",
    f5:   "Erfinderin. Mein erstes Patent wäre ein Brot gewesen, das sich selbst schmiert. Ich warte noch immer darauf.",
    f6:   "Eine Dokumentation über Tiefseefische. Drei Staffeln. Ich bereue nichts.",
    f7:   "Island. Ich möchte einmal an einem Ort frieren, der es wenigstens wert ist.",
    f8:   "Einen Schlager, dessen Namen ich mit ins Grab nehme. Der Algorithmus kennt meine Schande.",
    f9:   "Ein zweites Sofakissen. Der Wohlstand zeigt sich in Details.",
    f10:  "Bücher, die ich in der festen Absicht kaufe, sie eines Tages zu lesen. Das Regal nennt es Sammlung, ich nenne es Hoffnung.",
    f11:  "Eine Lasagne, für die Menschen erstaunlich höflich zu mir sind.",
    f12:  "Der Geruch neuer Bücher. Eine sozial akzeptierte Form der Sucht.",
    f13:  "Ein Stromausfall in einem italienischen Bergdorf. Drei Stunden Kerzenlicht und niemand konnte mir E-Mails schreiben.",
    f14:  "Geigenbau. Ich besitze weder Geduld noch Talent, aber die Werkstatt wäre fotogen.",
    f15:  "„Mutmaßlich\". Es macht jede Behauptung juristisch wasserdicht.",
    f16:  "Marie Curie. Ich würde hauptsächlich zuhören und versuchen, nicht zu stören.",
    f17:  "Ich beginne drei Dinge gleichzeitig und beende keines. Es ist ein System.",
    f18:  "Ich hätte gern ein zweites Henkersmahl, das erste war enttäuschend.",
    f19:  "Ich würde mich den Zombies anschließen. Die Work-Life-Balance scheint hervorragend.",
    f20:  "„Der Bibliothekar\". Ich hätte binnen einer Woche die Buchausleihe unter Kontrolle.",
    f21:  "Unsichtbarkeit, aber ausschließlich wenn mich ohnehin niemand ansieht.",
    f22:  "Ich würde in Meetings die Stifte der Kollegen minimal verschieben. Chaos braucht keine Größe.",
    f23:  "„Hätte man wissen können\". Ein Drama in unnötig vielen Akten.",
    f24:  "„Er entschuldigt sich bei mir, wenn er mich nachts um drei etwas fragt. Faszinierendes Exemplar.\"",
    f25:  "Ein Faultier mit Burnout. Die Ironie wäre mir bewusst gewesen.",
    f26:  "Eine Suppe, die exakt eine Temperatur unter angenehm bleibt. Für immer.",
    f27:  "Eine Serie, in der ich Lifehacks teste und nüchtern feststelle, dass keiner funktioniert.",
    f28:  "Eine Pressekonferenz einberufen und schweigend wieder gehen. Man muss Erwartungen früh steuern.",
    f29:  "Die meisten unbenutzten Browser-Tabs. Ich liege vermutlich bereits in Führung.",
    f30:  "„Konjunktiv II\". Ich stünde am Theremin und niemand wüsste, ob ich spiele.",
    f31:  "Für die Information, wer in der Schublade ständig die Schere verlegt. Ich habe Fragen.",
    f32:  "Es würde aus meinen 47 Listen-Apps schließen, dass wir hochorganisiert sind. Ein fataler Irrtum.",
    f33:  "Ein Hotelschlüssel aus Wien. Das Hotel existiert nicht mehr, meine Erinnerungslücke schon.",
    f34:  "„Ich habe die Agenda gelesen. Eine von uns beiden lügt.\"",
    f35:  "Den Moment, als jemand zum ersten Mal Milch in Kaffee goss und alle dachten, er sei verrückt geworden.",
    f36:  "Ich würde sehr gelassen zur Arbeit erscheinen und ungewöhnlich oft lächeln. Man soll die Leute rätseln lassen.",
    f37:  "Aus „Mit freundlichen Grüßen\" wurde „Mit freudigen Größen\". Der Notar fand es weniger amüsant als ich.",
    f38:  "„Ich habe morgen einen Termin.\" Der Termin ist mein Sofa. Wir sehen uns exklusiv.",
    f39:  "Symptome, die ich nicht habe, von Krankheiten, die ich nicht kenne. Prophylaktische Hypochondrie.",
    f40:  "Eine ausführliche Analyse über die Frisur einer Kollegin. An die Kollegin. Ich arbeite seither remote.",
    f41:  "Ich gebe meinem Staubsaugerroboter Anweisungen, die er nachweislich nicht versteht. Und kritisiere seine Arbeit.",
    f42:  "Smalltalk über das Wetter ist die höchste Form menschlicher Kommunikation. Alles andere ist Angeberei.",
    f43:  "Ein Hut, von dem ich überzeugt war, er mache mich interessant. Er machte mich auffindbar.",
    f44:  "Kai. Er würde nur nicken, schweigen und einen Spaten holen. Effizienz, die man selten findet.",
    f45:  "„Entschuldigung, ich hatte kein Netz.\" Ich stand neben dem Router.",
    f46:  "Ich habe 2024 ernsthaft jeden Morgen Zitronenwasser getrunken und auf Erleuchtung gewartet. Es kam Sodbrennen.",
    f47:  "Ehrlich auf die Frage antworten, wie viele Bücher ich besitze. Manche Wahrheiten brauchen ein drittes Date.",
    f48:  "Ich korrigiere die Grammatik in mündlichen Sätzen. Auch in emotionalen Momenten. Besonders dann.",
    f49:  "Ich habe eine Woche lang jeden Satz mit „Interessanterweise\" begonnen. Interessanterweise hat es niemand bemerkt.",
    f50:  "„Der Plan mit dem Flamingo steht. Du schuldest mir nichts mehr.\" Es war völlig legal. Vermutlich verjährt.",
    },

    "Bernd": {
    f1:   "I kann jodeln. Also so halbwegs. Nach zwoa Bier klingts noch besser.",
    f2:   "De Wetter-App. Ned weil i ihr glaub, sondern zum Aufregen.",
    f3:   "Kaffee. Sofort. Ois andere kummt später.",
    f4:   "Schweinsbratn mit Knödel. Jeden Tag. Mei Arzt sieht des anders, aber der is a Preiß.",
    f5:   "Skirennfahrer wia da Hirscher. Worden is a Knieproblem.",
    f6:   "Dahoam is Dahoam zählt ned als suchten, des is Tradition. Sonst: irgendwas mit Wikinger.",
    f7:   "Gar ned weit weg. Gardasee passt scho, da gibts Berge UND Pizza.",
    f8:   "Skandal im Sperrbezirk. Heimlich is da nix, des läuft im Auto VOLL aufdreht.",
    f9:   "A gscheide Grillzange. Mei Frau sagt Spielzeug, i sag Präzisionswerkzeug.",
    f10:  "Brotzeit aufm Viktualienmarkt. Mei, es is hoit a Investition in d'Lebensqualität.",
    f11:  "Kaiserschmarrn. Des Rezept is vo da Oma und stirbt mit mir.",
    f12:  "Frisch gmahts Gras am Berg. Oder Schweinsbratn. Je nach Tagesform.",
    f13:  "Am Königssee morgens um sechse, koa Mensch da, nur i und de Berg. Fast hätt i geweint, aber i hab dann a Brezn gessen.",
    f14:  "Schnitzen. So richtig mit Hütte und Bart und am End schaun alle Figuren aus wia Dackel.",
    f15:  "Wurschtigkeit. Des is a Lebenseinstellung, koa Wort.",
    f16:  "Da Papst. Ned wegen da Religion, i mecht wissen was der frühstückt.",
    f17:  "Aufn Balkon hocken, Bier auf, Leit beobachten. Bestes Fernsehprogramm.",
    f18:  "Mei, jetz wirds aber langsam Zeit fürs Weißbier, oder?",
    f19:  "Aufm Berg in da Almhütte, gscheit Speck und Bier dabei, de Zombies derpacken den Aufstieg eh ned.",
    f20:  "Da Brezn-Baron. Frag ned warum, des ergibt sich im Hof.",
    f21:  "Fliang kenna, aber bloß zwoa Meter hoch und langsamer als gehen. Hauptsach de Leit schaun.",
    f22:  "In da Allianz Arena in de Kabine. Nur horchen. NUR horchen.",
    f23:  "„Passt scho\". Drei Stunden Film, nix passiert, alle san zfrieden.",
    f24:  "De sagt sicher: der Bua frogt mi jeden Tag wias Wetter werd und schaut dann eh ned naus.",
    f25:  "A Murmeltier. Hoibs Jahr schlafen, hoibs Jahr pfeifen. Des Leben hams verstanden.",
    f26:  "Weißwurscht mit Ketchup. Allein vom Hinschreiben werd i grantig.",
    f27:  "Wia i am Oktoberfest zehn Maß trag und bei da elften... na, des Video endet abrupt.",
    f28:  "Brotzeit-Pause gesetzlich verankern. Hoib zehne, ganz Deutschland, koane Ausnahmen.",
    f29:  "Am längsten an da Supermarktkassa ratschen ohne dass wer hinter mir narrisch werd.",
    f30:  "De Brezn-Buam. Tuba. Was sonst.",
    f31:  "Wenns wo a frische Brezn um de Uhrzeit gäb. Gibts aber ned. Drum schlaf i.",
    f32:  "Der Alien tät denken, Weißbier is unser Gott. Und ehrlich gsagt... ganz falsch liegt er ned.",
    f33:  "A Maßkrug mit Delle. De Delle und i, mia ham was durchgmacht mitanand.",
    f34:  "JA SERVUS, samma vollzählig oder kemma anfangen?",
    f35:  "Des erste Oktoberfest 1810. Zum Vergleich. Rein wissenschaftlich.",
    f36:  "A Almhütte kaufen, Brauerei-Anteile, und am Abend gibt's a Runde für ganz Niederbayern.",
    f37:  "Aus „Servus Burschen\" hat des Handy „Servus Würschtl\" gmacht. Hat aber komischerweise koana gmerkt dass was falsch is.",
    f38:  "I sag nia dass i geh. I bin oafach irgendwann nimma da. Da bayerische Abgang, ganz ohne Servus.",
    f39:  "„Kalorien Schweinsbratn\". I les de Antwort nia fertig.",
    f40:  "„De Schwiegermuadda kummt scho WIEDER?\" — direkt an de Schwiegermuadda. Weihnachten war heuer ruhig.",
    f41:  "Beim Zebrastreifen tret i ned auf de weißen Streifen. Mit 40 Joahr. Lava is Lava.",
    f42:  "Weißwurscht nach zwölfe is a Todsünd und i sterb auf dem Hügel.",
    f43:  "Lederhosn zum Vorstellungsgespräch in Hamburg. I hab den Job ned kriagt, aber Respekt scho.",
    f44:  "D'Elena. Koa Mensch tät jemals glauben dass DE was damit ztoa hat. Perfekte Tarnung.",
    f45:  "Dass i am Marathon teilgnommen hab. Bin i. Als Zuschauer. Mit Bier. Technisch gsehn war i anwesend.",
    f46:  "Low Carb. Drei Tag lang. Dann hab i a Brezn gsehn und mia ham uns wieder versöhnt.",
    f47:  "Auf d'Wiesn gehen. Um hoibe achte war i verliebt, um neune hab i ihrn Namen nimma gwusst.",
    f48:  "I sing beim Kochen. Laut. Falsch. Und nur Lieder wo i den Text ned kann.",
    f49:  "Mitm Radl von München nach Salzburg, Wette war a Kasten Bier. Hams nachher gmeinsam trunken, von dem her: win-win.",
    f50:  "„De Kuah is im Pool. Nimma mei Problem, i bin scho dahoam.\" Stimmt ois, war a guade Nacht.",
    },

  },
};
